/**
 * Render `results/latest.json` as the README's simulation table. The numbers are never typed by
 * hand: this is the only path from the harness to prose, and the caption names the model commit
 * the run was made at so a reader can regenerate it.
 *
 *     bun run packages/sim-report/render.ts            # markdown to stdout
 */

export type Regime = {
	regime: string
	trendBps: number
	volBpsPerTick: number
	seeds: number
	meanVsStatic: number
	sdVsStatic: number
	worstVsStatic: number
	seedsAhead: number
	meanBookDrift: number
	meanVsStaticBpsOfBook: number
	worstVsStaticBpsOfBook: number
}

export type Report = {
	modelCommit: string
	generatedAt: string
	unit: string
	bookInA: number
	regimes: Regime[]
}

const fmt = (n: number): string => n.toLocaleString('en-US', { maximumFractionDigits: 0 })

export const renderMarkdown = (report: Report): string => {
	const lines = [
		'| Regime | Trend | Vol / tick | Mean vs static | of book | Std dev | Worst | Seeds ahead | Book drift |',
		'|---|---:|---:|---:|---:|---:|---:|---:|---:|',
	]
	for (const r of report.regimes) {
		lines.push(
			`| ${r.regime} | ${r.trendBps} bps | ${r.volBpsPerTick} bps | ${fmt(r.meanVsStatic)} | ${r.meanVsStaticBpsOfBook.toFixed(1)} bps | ${fmt(r.sdVsStatic)} | ${fmt(r.worstVsStatic)} | ${r.seedsAhead}/${r.seeds} | ${r.meanBookDrift.toFixed(4)} |`,
		)
	}
	lines.push('')
	lines.push(
		`Trading PnL of the reservation policy against a static constant-product control, ${report.unit}, on an opening book of ${fmt(report.bookInA)} raw tokenA. ` +
			`Generated by \`packages/sim-report/run.py\` at model commit \`${report.modelCommit.slice(0, 12)}\` on ${report.generatedAt}.`,
	)
	return lines.join('\n') + '\n'
}

if (import.meta.main) {
	const report = (await Bun.file(new URL('./results/latest.json', import.meta.url)).json()) as Report
	process.stdout.write(renderMarkdown(report))
}
