import { writeFileSync } from "node:fs";
import { LEGS } from "@zentis/console-data";
import historySepolia from "../../../packages/console-data/fixtures/history-sepolia.json" with { type: "json" };
import historyArbitrum from "../../../packages/console-data/fixtures/history-arbitrum-sepolia.json" with { type: "json" };
import historyBase from "../../../packages/console-data/fixtures/history-base-sepolia.json" with { type: "json" };

/**
 * The recorded transaction log the demo falls back on, built out of what was really sent.
 *
 * `ZENTIS_FIXTURES=1` runs the console against a recorded world, and the log page is part of that
 * world: a demo whose log is empty says the console cannot show one. Every line below is generated
 * from the indexed fixtures — real hashes, real sizes, real times, on the chains they happened on —
 * so nothing on that page is a number somebody typed.
 *
 * It is written as a module rather than read from a file because the console ships as one binary:
 * a fixture beside the source is not there on the machine the binary is copied to.
 *
 * Run: `bun run scripts/record-txlog.ts` from `apps/tui`.
 */
interface RawFill {
  timestamp: string;
  transaction: string;
  amountIn: string;
  amountOut: string;
  isAToB: boolean;
}
interface RawReference {
  timestamp: string;
  transaction: string;
  seq: number;
}
interface RawHistory {
  fills: RawFill[];
  references: RawReference[];
}

const iso = (seconds: string) => new Date(Number(seconds) * 1000).toISOString().replace(/\.\d{3}Z$/, "Z");

/** How many publishes per leg are kept: enough that the page is a page, not the whole recording. */
const PUBLISHES = 4;

const lines = LEGS.flatMap((leg, index) => {
  const history = [historySepolia, historyArbitrum, historyBase][index] as unknown as RawHistory;
  const fills = history.fills.map((fill) => ({
    at: iso(fill.timestamp),
    chain: leg.name,
    chainId: leg.chainId,
    kind: "fill",
    // The indexed record does not say who sent it: a taker is whoever called the router, and the
    // subgraph stores the fill rather than the sender. Left absent rather than filled with a guess.
    actor: null,
    tx: fill.transaction,
    status: 1,
    amountIn: fill.amountIn,
    amountOut: fill.amountOut,
    tokenIn: fill.isAToB ? leg.tokenA.address : leg.tokenB.address,
    tokenOut: fill.isAToB ? leg.tokenB.address : leg.tokenA.address,
    note: null,
  }));
  const publishes = history.references.slice(0, PUBLISHES).map((ref) => ({
    at: iso(ref.timestamp),
    chain: leg.name,
    chainId: leg.chainId,
    kind: "republish",
    actor: null,
    tx: ref.transaction,
    status: 1,
    amountIn: null,
    amountOut: null,
    tokenIn: null,
    tokenOut: null,
    note: `seq ${ref.seq}`,
  }));
  return [...fills, ...publishes];
}).sort((a, b) => Date.parse(a.at) - Date.parse(b.at));

const body = `${lines.map((line) => JSON.stringify(line)).join("\n")}\n`;
const source = `/**
 * The recorded transaction log, generated by \`scripts/record-txlog.ts\` from the indexed fixtures.
 *
 * Every line is a transaction that was really sent, on the chain it was sent on, at the size it was
 * sent at. Do not edit by hand: re-run the script against a newer recording instead.
 */
export const RECORDED_TXLOG = ${JSON.stringify(body)};
`;
writeFileSync(new URL("../src/txlog-fixture.ts", import.meta.url), source);
process.stdout.write(`${lines.length} lines recorded\n`);
