import { describe, expect, test } from 'bun:test'
import vectors from './allocation_vectors.json'
import { allocateBandEdge, contestedBps } from './policy'

/**
 * The allocation in the workflow has to agree with the Python reference model exactly, because the
 * model is what the simulation and the write-up run on. Vectors are generated by
 * packages/reference-model/scripts/generate_allocation_fixtures.py under a pinned seed.
 */
const strength = BigInt(vectors.strengthBps)
const minEdge = BigInt(vectors.minEdgeBps)
const maxEdge = BigInt(vectors.maxEdgeBps)

describe('allocation matches the reference model', () => {
	for (const example of vectors.cases) {
		test(example.name, () => {
			const got = allocateBandEdge(
				BigInt(example.baseEdgeBps),
				example.ownLeans.map((v) => BigInt(v)),
				example.crowdingBps.map((v) => BigInt(v)),
				strength,
				minEdge,
				maxEdge,
			)
			expect(got.map((v) => v.toString())).toEqual(example.expected)
		})
	}
})

describe('the properties the allocation must not lose', () => {
	// Zero reads as "nothing published" to the instruction, so a throttled leg would silently become
	// an unbounded one. This is the single most important invariant here.
	test('no leg is ever allocated zero', () => {
		for (const example of vectors.cases) {
			for (const v of example.expected) expect(BigInt(v) >= minEdge).toBe(true)
		}
	})

	test('no leg exceeds the ceiling the maker set', () => {
		for (const example of vectors.cases) {
			for (const v of example.expected) expect(BigInt(v) <= maxEdge).toBe(true)
		}
	})

	// Without crowding data the allocation must be indistinguishable from the flat budget the
	// system published before it existed, or adding it would be a silent behaviour change.
	test('with no crowding anywhere every leg keeps the base budget', () => {
		const base = 57n
		const got = allocateBandEdge(base, [100n, -50n, 10n], [0n, 0n, 0n], strength, minEdge, maxEdge)
		expect(got).toEqual([base, base, base])
	})

	test('a venue leaning against us is a counterparty, not competition', () => {
		expect(contestedBps(100n, -9000n)).toBe(0n)
		expect(contestedBps(-100n, 9000n)).toBe(0n)
	})

	test('a venue leaning with us is contested by its full magnitude', () => {
		expect(contestedBps(100n, 9000n)).toBe(9000n)
		expect(contestedBps(-100n, -9000n)).toBe(9000n)
	})

	test('a flat side on either end is not evidence of contention', () => {
		expect(contestedBps(0n, 9000n)).toBe(0n)
		expect(contestedBps(100n, 0n)).toBe(0n)
	})

	test('a mismatched leg count is refused rather than silently truncated', () => {
		expect(() => allocateBandEdge(57n, [1n, 2n], [0n], strength, minEdge, maxEdge)).toThrow()
	})

	test('a floor of zero is refused, because zero means unpublished', () => {
		expect(() => allocateBandEdge(57n, [1n], [0n], strength, 0n, maxEdge)).toThrow()
	})
})
