import { describe, expect, test } from 'bun:test'
import vectors from './markout_vectors.json'
import { markoutBps, toBase64, type MarkoutFill, type MarkoutReference } from './policy'

/**
 * The workflow's markout has to agree with the Python reference model exactly, because the model is
 * what the simulation and the write-up run on. The vectors are generated by
 * packages/reference-model/scripts/generate_markout_fixtures.py under a pinned seed; regenerate and
 * commit the diff if the model changes.
 */
const horizon = BigInt(vectors.horizonSeconds)
const cap = BigInt(vectors.capBps)

const asFills = (raw: (typeof vectors.cases)[number]['fills']): MarkoutFill[] =>
	raw.map((f) => ({
		timestamp: BigInt(f.timestamp),
		isAToB: f.isAToB,
		amountIn: BigInt(f.amountIn),
		amountOut: BigInt(f.amountOut),
	}))

const asReferences = (raw: (typeof vectors.cases)[number]['references']): MarkoutReference[] =>
	raw.map((r) => ({ updatedAt: BigInt(r.updatedAt), mid: BigInt(r.mid) }))

describe('markout matches the reference model', () => {
	for (const example of vectors.cases) {
		test(example.name, () => {
			const result = markoutBps(asFills(example.fills), asReferences(example.references), horizon, cap)
			expect(result.matured).toBe(example.expected.matured)
			expect(result.skipped).toBe(example.expected.skipped)
			expect(result.weightedBps.toString()).toBe(example.expected.weightedBps)
			expect(result.publishedBps.toString()).toBe(example.expected.publishedBps)
		})
	}
})

describe('the published term is bounded by construction', () => {
	test('a favourable markout never narrows the spread', () => {
		for (const example of vectors.cases) {
			const result = markoutBps(asFills(example.fills), asReferences(example.references), horizon, cap)
			expect(result.publishedBps >= 0n).toBe(true)
			expect(result.publishedBps <= cap).toBe(true)
		}
	})

	test('every fill either matures or is skipped, never both and never neither', () => {
		for (const example of vectors.cases) {
			const result = markoutBps(asFills(example.fills), asReferences(example.references), horizon, cap)
			expect(result.matured + result.skipped).toBe(example.fills.length)
		}
	})
})

describe('base64 for the request body', () => {
	// The body has to survive the protobuf JSON round trip, so it is checked against a known-good
	// decoder rather than against hand-written expectations. Padding and multi-byte input are the
	// two things a hand-rolled encoder gets wrong.
	const cases = ['', 'f', 'fo', 'foo', 'foob', '{"query":"{ fills { amountIn } }"}', 'ÿþ€']

	for (const input of cases) {
		test(`round-trips ${JSON.stringify(input)}`, () => {
			const bytes = new TextEncoder().encode(input)
			expect(toBase64(bytes)).toBe(Buffer.from(bytes).toString('base64'))
		})
	}
})
