import { describe, expect, test } from 'bun:test'
import vectors from '../fast/reservation_vectors.json'
import { legWeight, reservation } from './policy'

/**
 * The policy in the workflow has to agree with the Python reference model exactly, because the
 * model is what the harness and the write-up run on. Vectors are generated by
 * packages/reference-model/scripts/generate_reservation_fixtures.py under a pinned seed.
 */
const mid = BigInt(vectors.mid)
const maxTilt = BigInt(vectors.maxTiltBps)

describe('reservation policy against the reference model', () => {
	for (const c of vectors.cases) {
		test(c.name, () => {
			const legs = c.legs.map(([a, b]) => legWeight({ balanceA: BigInt(a), balanceB: BigInt(b), mid }))
			const out = reservation(legs, BigInt(c.kappaOwnBps), BigInt(c.kappaBookBps), maxTilt)
			expect(out.map((p) => p.tiltBps.toString())).toEqual(c.expected.map((e) => e.tiltBps))
			expect(out.map((p) => p.dTiltPerA.toString())).toEqual(c.expected.map((e) => e.dTiltPerA))
		})
	}
})
