import { describe, expect, test } from 'bun:test'
import vectors from './volatility_vectors.json'
import { isqrt, sigmaOverHorizonBps, volatilitySpreadBps, type PriceSample } from './policy'

/**
 * The workflow's volatility has to agree with the Python reference model exactly, because the model
 * is what the harness and the write-up run on. Vectors are generated by
 * packages/reference-model/scripts/generate_volatility_fixtures.py under a pinned seed.
 */
const horizon = BigInt(vectors.horizonSeconds)
const multiplier = BigInt(vectors.multiplierBps)
const cap = BigInt(vectors.capBps)

const asSamples = (raw: string[][]): PriceSample[] =>
	raw.map(([t, m]) => ({ timestamp: BigInt(t as string), mid: BigInt(m as string) }))

describe('isqrt', () => {
	test('is the floor of the root', () => {
		for (const n of [0n, 1n, 2n, 3n, 4n, 15n, 16n, 17n, 10n ** 18n, 10n ** 18n + 1n, (1n << 127n) - 1n]) {
			const r = isqrt(n)
			expect(r * r <= n && n < (r + 1n) * (r + 1n)).toBe(true)
		}
	})
})

describe('volatility matches the reference model', () => {
	for (const c of vectors.cases) {
		test(c.name, () => {
			const samples = asSamples(c.samples)
			expect(sigmaOverHorizonBps(samples, horizon).toString()).toBe(c.sigmaBps)
			expect(volatilitySpreadBps(samples, horizon, multiplier, cap).toString()).toBe(c.spreadTermBps)
		})
	}
})
